# Generated by Django 3.1.6 on 2021-04-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('technology', models.CharField(max_length=20, null=True)),
                ('image', models.FilePathField(null=True, path='static/img')),
            ],
        ),
    ]
